language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"

services:
  - mongodb

before_install:
  - go get -t ./...

script:
  - go test -v -race -coverprofile=coverage.txt .
  - go tool vet .

after_success:
- bash <(curl -s https://codecov.io/bash)
